// <auto-generated>
// Metadados dos cadastros simples, usados pela página CRUD genérica (GenericCrudPage).
// Gerado a partir do modelo de dados do backend.
// </auto-generated>

export interface CrudFieldMeta {
  name: string;
  label: string;
  type: "text" | "number" | "boolean" | "date";
  required: boolean;
}

export interface CrudFkMeta {
  name: string;
  label: string;
  resource: string;
  required: boolean;
  optionLabelField: string;
}

export interface CrudModuleMeta {
  key: string;
  entity: string;
  label: string;
  group: string;
  resource: string;
  idType: "string" | "number";
  fields: CrudFieldMeta[];
  fks: CrudFkMeta[];
}

export const CADASTRO_MODULES: CrudModuleMeta[] = [
  {
    "key": "estado",
    "entity": "Estado",
    "label": "Estado",
    "group": "Cadastros Gerais",
    "resource": "estado",
    "idType": "number",
    "fields": [
      {
        "name": "descricao",
        "label": "Descricao",
        "type": "text",
        "required": true
      },
      {
        "name": "sigla",
        "label": "Sigla",
        "type": "text",
        "required": true
      }
    ],
    "fks": []
  },
  {
    "key": "cidade",
    "entity": "Cidade",
    "label": "Cidade",
    "group": "Cadastros Gerais",
    "resource": "cidade",
    "idType": "number",
    "fields": [
      {
        "name": "descricao",
        "label": "Descricao",
        "type": "text",
        "required": true
      }
    ],
    "fks": [
      {
        "name": "estadoid",
        "label": "Estado",
        "resource": "estado",
        "required": true,
        "optionLabelField": "descricao"
      }
    ]
  },
  {
    "key": "endereco",
    "entity": "Endereco",
    "label": "Endereço",
    "group": "Cadastros Gerais",
    "resource": "endereco",
    "idType": "number",
    "fields": [
      {
        "name": "cep",
        "label": "Cep",
        "type": "text",
        "required": true
      },
      {
        "name": "rua",
        "label": "Rua",
        "type": "text",
        "required": true
      },
      {
        "name": "bairro",
        "label": "Bairro",
        "type": "text",
        "required": true
      },
      {
        "name": "numero",
        "label": "Numero",
        "type": "number",
        "required": true
      },
      {
        "name": "complemento",
        "label": "Complemento",
        "type": "text",
        "required": false
      }
    ],
    "fks": [
      {
        "name": "cidadeid",
        "label": "Cidade",
        "resource": "cidade",
        "required": true,
        "optionLabelField": "descricao"
      }
    ]
  },
  {
    "key": "cliFor",
    "entity": "CliFor",
    "label": "Cliente / Fornecedor",
    "group": "Cadastros Gerais",
    "resource": "cliFor",
    "idType": "string",
    "fields": [
      {
        "name": "cnpj",
        "label": "Cnpj",
        "type": "text",
        "required": false
      },
      {
        "name": "cpf",
        "label": "Cpf",
        "type": "text",
        "required": false
      },
      {
        "name": "tipopessoa",
        "label": "Tipopessoa",
        "type": "text",
        "required": true
      },
      {
        "name": "nome",
        "label": "Nome",
        "type": "text",
        "required": true
      },
      {
        "name": "nomefantasia",
        "label": "Nomefantasia",
        "type": "text",
        "required": false
      },
      {
        "name": "email",
        "label": "Email",
        "type": "text",
        "required": false
      },
      {
        "name": "telefone",
        "label": "Telefone",
        "type": "text",
        "required": false
      },
      {
        "name": "celular",
        "label": "Celular",
        "type": "text",
        "required": false
      },
      {
        "name": "tipocliente",
        "label": "Tipocliente",
        "type": "text",
        "required": false
      }
    ],
    "fks": [
      {
        "name": "enderecoid",
        "label": "Endereço",
        "resource": "endereco",
        "required": false,
        "optionLabelField": "cep"
      }
    ]
  },
  {
    "key": "centroCusto",
    "entity": "CentroCusto",
    "label": "Centro de Custo",
    "group": "Cadastros Gerais",
    "resource": "centroCusto",
    "idType": "number",
    "fields": [
      {
        "name": "nome",
        "label": "Nome",
        "type": "text",
        "required": true
      }
    ],
    "fks": [
      {
        "name": "cliforid",
        "label": "Cliente / Fornecedor",
        "resource": "cliFor",
        "required": true,
        "optionLabelField": "cnpj"
      }
    ]
  },
  {
    "key": "contaCorrente",
    "entity": "ContaCorrente",
    "label": "Conta Corrente",
    "group": "Financeiro",
    "resource": "contaCorrente",
    "idType": "number",
    "fields": [
      {
        "name": "descricao",
        "label": "Descricao",
        "type": "text",
        "required": true
      },
      {
        "name": "agencia",
        "label": "Agencia",
        "type": "number",
        "required": true
      },
      {
        "name": "conta",
        "label": "Conta",
        "type": "text",
        "required": true
      },
      {
        "name": "codbanco",
        "label": "Codbanco",
        "type": "number",
        "required": true
      }
    ],
    "fks": [
      {
        "name": "cliforid",
        "label": "Cliente / Fornecedor",
        "resource": "cliFor",
        "required": true,
        "optionLabelField": "cnpj"
      }
    ]
  },
  {
    "key": "especie",
    "entity": "Especie",
    "label": "Espécie",
    "group": "Financeiro",
    "resource": "especie",
    "idType": "number",
    "fields": [
      {
        "name": "descricao",
        "label": "Descricao",
        "type": "text",
        "required": true
      }
    ],
    "fks": []
  },
  {
    "key": "pagamento",
    "entity": "Pagamento",
    "label": "Pagamento",
    "group": "Financeiro",
    "resource": "pagamento",
    "idType": "number",
    "fields": [
      {
        "name": "valorpago",
        "label": "Valorpago",
        "type": "number",
        "required": true
      },
      {
        "name": "datapagamento",
        "label": "Datapagamento",
        "type": "date",
        "required": true
      },
      {
        "name": "descricao",
        "label": "Descricao",
        "type": "text",
        "required": false
      }
    ],
    "fks": [
      {
        "name": "contapagarid",
        "label": "Conta a Pagar",
        "resource": "contaPagar",
        "required": true,
        "optionLabelField": "descricao"
      },
      {
        "name": "especieid",
        "label": "Espécie",
        "resource": "especie",
        "required": true,
        "optionLabelField": "descricao"
      },
      {
        "name": "contacorrenteid",
        "label": "Conta Corrente",
        "resource": "contaCorrente",
        "required": true,
        "optionLabelField": "descricao"
      },
      {
        "name": "cliforid",
        "label": "Cliente / Fornecedor",
        "resource": "cliFor",
        "required": true,
        "optionLabelField": "cnpj"
      }
    ]
  },
  {
    "key": "recebimento",
    "entity": "Recebimento",
    "label": "Recebimento",
    "group": "Financeiro",
    "resource": "recebimento",
    "idType": "number",
    "fields": [
      {
        "name": "valorrecebido",
        "label": "Valorrecebido",
        "type": "number",
        "required": true
      },
      {
        "name": "datarecebimento",
        "label": "Datarecebimento",
        "type": "date",
        "required": true
      },
      {
        "name": "descricao",
        "label": "Descricao",
        "type": "text",
        "required": false
      }
    ],
    "fks": [
      {
        "name": "contareceberid",
        "label": "Conta a Receber",
        "resource": "contaReceber",
        "required": true,
        "optionLabelField": "descricao"
      },
      {
        "name": "especieid",
        "label": "Espécie",
        "resource": "especie",
        "required": true,
        "optionLabelField": "descricao"
      },
      {
        "name": "contacorrenteid",
        "label": "Conta Corrente",
        "resource": "contaCorrente",
        "required": true,
        "optionLabelField": "descricao"
      },
      {
        "name": "cliforid",
        "label": "Cliente / Fornecedor",
        "resource": "cliFor",
        "required": true,
        "optionLabelField": "cnpj"
      }
    ]
  },
  {
    "key": "historico",
    "entity": "Historico",
    "label": "Histórico Padrão",
    "group": "Lançamentos",
    "resource": "historico",
    "idType": "number",
    "fields": [
      {
        "name": "descricao",
        "label": "Descricao",
        "type": "text",
        "required": true
      },
      {
        "name": "historico",
        "label": "Historico",
        "type": "text",
        "required": true
      }
    ],
    "fks": []
  },
  {
    "key": "unidadeMedida",
    "entity": "UnidadeMedida",
    "label": "Unidade de Medida",
    "group": "Cadastros de Produtos",
    "resource": "unidadeMedida",
    "idType": "number",
    "fields": [
      {
        "name": "descricao",
        "label": "Descricao",
        "type": "text",
        "required": true
      },
      {
        "name": "sigla",
        "label": "Sigla",
        "type": "text",
        "required": true
      }
    ],
    "fks": [
      {
        "name": "cliforid",
        "label": "Cliente / Fornecedor",
        "resource": "cliFor",
        "required": true,
        "optionLabelField": "cnpj"
      }
    ]
  },
  {
    "key": "marca",
    "entity": "Marca",
    "label": "Marca",
    "group": "Cadastros de Produtos",
    "resource": "marca",
    "idType": "number",
    "fields": [
      {
        "name": "nome",
        "label": "Nome",
        "type": "text",
        "required": true
      }
    ],
    "fks": [
      {
        "name": "cliforid",
        "label": "Cliente / Fornecedor",
        "resource": "cliFor",
        "required": true,
        "optionLabelField": "cnpj"
      }
    ]
  },
  {
    "key": "grupo",
    "entity": "Grupo",
    "label": "Grupo de Produto",
    "group": "Cadastros de Produtos",
    "resource": "grupo",
    "idType": "number",
    "fields": [
      {
        "name": "descricao",
        "label": "Descricao",
        "type": "text",
        "required": true
      }
    ],
    "fks": [
      {
        "name": "cliforid",
        "label": "Cliente / Fornecedor",
        "resource": "cliFor",
        "required": true,
        "optionLabelField": "cnpj"
      }
    ]
  },
  {
    "key": "local",
    "entity": "Local",
    "label": "Local de Estoque",
    "group": "Cadastros de Produtos",
    "resource": "local",
    "idType": "number",
    "fields": [
      {
        "name": "descricao",
        "label": "Descricao",
        "type": "text",
        "required": true
      }
    ],
    "fks": [
      {
        "name": "cliforid",
        "label": "Cliente / Fornecedor",
        "resource": "cliFor",
        "required": true,
        "optionLabelField": "cnpj"
      }
    ]
  },
  {
    "key": "produto",
    "entity": "Produto",
    "label": "Produto",
    "group": "Cadastros de Produtos",
    "resource": "produto",
    "idType": "number",
    "fields": [
      {
        "name": "nome",
        "label": "Nome",
        "type": "text",
        "required": true
      },
      {
        "name": "descricao",
        "label": "Descricao",
        "type": "text",
        "required": true
      },
      {
        "name": "quantidademinima",
        "label": "Quantidademinima",
        "type": "number",
        "required": true
      }
    ],
    "fks": [
      {
        "name": "cliforid",
        "label": "Cliente / Fornecedor",
        "resource": "cliFor",
        "required": true,
        "optionLabelField": "cnpj"
      },
      {
        "name": "grupoid",
        "label": "Grupo de Produto",
        "resource": "grupo",
        "required": true,
        "optionLabelField": "descricao"
      },
      {
        "name": "marcaid",
        "label": "Marca",
        "resource": "marca",
        "required": true,
        "optionLabelField": "nome"
      },
      {
        "name": "unidademedidaid",
        "label": "Unidade de Medida",
        "resource": "unidadeMedida",
        "required": true,
        "optionLabelField": "descricao"
      },
      {
        "name": "fornecedorid",
        "label": "Cliente / Fornecedor",
        "resource": "cliFor",
        "required": true,
        "optionLabelField": "cnpj"
      }
    ]
  },
  {
    "key": "preco",
    "entity": "Preco",
    "label": "Preço",
    "group": "Cadastros de Produtos",
    "resource": "preco",
    "idType": "number",
    "fields": [
      {
        "name": "valor",
        "label": "Valor",
        "type": "number",
        "required": true
      },
      {
        "name": "datavigente",
        "label": "Datavigente",
        "type": "date",
        "required": true
      }
    ],
    "fks": [
      {
        "name": "produtoid",
        "label": "Produto",
        "resource": "produto",
        "required": false,
        "optionLabelField": "nome"
      }
    ]
  },
  {
    "key": "saldo",
    "entity": "Saldo",
    "label": "Saldo de Estoque",
    "group": "Cadastros de Produtos",
    "resource": "saldo",
    "idType": "number",
    "fields": [
      {
        "name": "qtde",
        "label": "Qtde",
        "type": "number",
        "required": true
      },
      {
        "name": "valor",
        "label": "Valor",
        "type": "number",
        "required": true
      }
    ],
    "fks": [
      {
        "name": "produtoid",
        "label": "Produto",
        "resource": "produto",
        "required": true,
        "optionLabelField": "nome"
      },
      {
        "name": "localid",
        "label": "Local de Estoque",
        "resource": "local",
        "required": true,
        "optionLabelField": "descricao"
      }
    ]
  },
  {
    "key": "fechaEstoque",
    "entity": "FechaEstoque",
    "label": "Fechamento de Estoque",
    "group": "Cadastros de Produtos",
    "resource": "fechaEstoque",
    "idType": "number",
    "fields": [
      {
        "name": "data",
        "label": "Data",
        "type": "date",
        "required": true
      },
      {
        "name": "customedio",
        "label": "Customedio",
        "type": "number",
        "required": true
      },
      {
        "name": "qtde",
        "label": "Qtde",
        "type": "number",
        "required": true
      }
    ],
    "fks": [
      {
        "name": "idproduto",
        "label": "Produto",
        "resource": "produto",
        "required": true,
        "optionLabelField": "nome"
      }
    ]
  },
  {
    "key": "grupoBem",
    "entity": "GrupoBem",
    "label": "Grupo de Bem",
    "group": "Patrimônio",
    "resource": "grupoBem",
    "idType": "number",
    "fields": [
      {
        "name": "descricao",
        "label": "Descricao",
        "type": "text",
        "required": true
      },
      {
        "name": "taxadepreciacao",
        "label": "Taxadepreciacao",
        "type": "number",
        "required": true
      },
      {
        "name": "vidautil",
        "label": "Vidautil",
        "type": "number",
        "required": true
      }
    ],
    "fks": [
      {
        "name": "cliforid",
        "label": "Cliente / Fornecedor",
        "resource": "cliFor",
        "required": true,
        "optionLabelField": "cnpj"
      }
    ]
  },
  {
    "key": "estadoConservacao",
    "entity": "EstadoConservacao",
    "label": "Estado de Conservação",
    "group": "Patrimônio",
    "resource": "estadoConservacao",
    "idType": "number",
    "fields": [
      {
        "name": "descricao",
        "label": "Descricao",
        "type": "text",
        "required": true
      }
    ],
    "fks": [
      {
        "name": "cliforid",
        "label": "Cliente / Fornecedor",
        "resource": "cliFor",
        "required": true,
        "optionLabelField": "cnpj"
      }
    ]
  },
  {
    "key": "motivoBaixa",
    "entity": "MotivoBaixa",
    "label": "Motivo de Baixa",
    "group": "Patrimônio",
    "resource": "motivoBaixa",
    "idType": "number",
    "fields": [
      {
        "name": "descricao",
        "label": "Descricao",
        "type": "text",
        "required": true
      }
    ],
    "fks": [
      {
        "name": "cliforid",
        "label": "Cliente / Fornecedor",
        "resource": "cliFor",
        "required": true,
        "optionLabelField": "cnpj"
      }
    ]
  },
  {
    "key": "depreciacao",
    "entity": "Depreciacao",
    "label": "Depreciação",
    "group": "Patrimônio",
    "resource": "depreciacao",
    "idType": "number",
    "fields": [
      {
        "name": "mes",
        "label": "Mes",
        "type": "number",
        "required": true
      },
      {
        "name": "ano",
        "label": "Ano",
        "type": "number",
        "required": true
      },
      {
        "name": "valordepreciado",
        "label": "Valordepreciado",
        "type": "number",
        "required": true
      },
      {
        "name": "valorreavaliado",
        "label": "Valorreavaliado",
        "type": "number",
        "required": true
      },
      {
        "name": "vidautil",
        "label": "Vidautil",
        "type": "number",
        "required": true
      },
      {
        "name": "taxadepreciacaomensal",
        "label": "Taxadepreciacaomensal",
        "type": "number",
        "required": true
      },
      {
        "name": "taxadepreciacaoanual",
        "label": "Taxadepreciacaoanual",
        "type": "number",
        "required": true
      },
      {
        "name": "valoratualizado",
        "label": "Valoratualizado",
        "type": "number",
        "required": true
      },
      {
        "name": "depreciacao",
        "label": "Depreciacao",
        "type": "number",
        "required": false
      },
      {
        "name": "datadepreciacao",
        "label": "Datadepreciacao",
        "type": "date",
        "required": true
      },
      {
        "name": "valoranual",
        "label": "Valoranual",
        "type": "number",
        "required": true
      },
      {
        "name": "valormes",
        "label": "Valormes",
        "type": "number",
        "required": true
      }
    ],
    "fks": [
      {
        "name": "patrimonioid",
        "label": "Patrimônio",
        "resource": "patrimonio",
        "required": true,
        "optionLabelField": "observacao"
      },
      {
        "name": "cliforid",
        "label": "Cliente / Fornecedor",
        "resource": "cliFor",
        "required": true,
        "optionLabelField": "cnpj"
      }
    ]
  },
  {
    "key": "despesaInvestimento",
    "entity": "DespesaInvestimento",
    "label": "Despesa / Investimento",
    "group": "Patrimônio",
    "resource": "despesaInvestimento",
    "idType": "number",
    "fields": [
      {
        "name": "data",
        "label": "Data",
        "type": "date",
        "required": true
      },
      {
        "name": "observacao",
        "label": "Observacao",
        "type": "text",
        "required": false
      },
      {
        "name": "valor",
        "label": "Valor",
        "type": "number",
        "required": true
      },
      {
        "name": "tipo",
        "label": "Tipo",
        "type": "text",
        "required": true
      }
    ],
    "fks": [
      {
        "name": "patrimonioid",
        "label": "Patrimônio",
        "resource": "patrimonio",
        "required": true,
        "optionLabelField": "observacao"
      },
      {
        "name": "cliforid",
        "label": "Cliente / Fornecedor",
        "resource": "cliFor",
        "required": true,
        "optionLabelField": "cnpj"
      }
    ]
  }
];
